### ISSUE TITLE
Add-SslCert check fails and tries to re-add ssl

### ISSUE THREAD

**Issue by matbutler** [microsoft/azure-pipelines-extensions#1039]
It appears to check $result.Get(4) for the Hostname:port, but its $result.Get(6) for me.

Windows 2022 
IIS Version 10.0.20348.1

**Comment by jiggybyte** [comment]
Hitting the same thing, it's because there are some extra lines of blank space when it calls the show sslcert....can we get a fix for this?  using Get(7) instead of Get(5) would solve it.

**Comment by jabteles** [comment]
+1 preventing to migrate to Server 2022. No more workarounds.

**Comment by v-schhabra** [comment]
Hi @jabteles, @jiggybyte 
The mentioned issue has been fixed in this PR https://github.com/microsoft/azure-pipelines-extensions/pull/1220
Could you please use the IISWebAppManagementV3 version of the task and test if it is working fine?

**Comment by jabteles** [comment]
> Hi @jabteles, @jiggybyte The mentioned issue has been fixed in this PR #1220 Could you please use the IISWebAppManagementV3 version of the task and test if it is working fine?

I updated the extension on my Azure DevOps and still get the same error
