### ISSUE TITLE
Windows Server 2022 is totally broken trying to add a binding

### ISSUE THREAD

**Issue by jiggybyte** [microsoft/azure-pipelines-extensions#1058]
The hard coded lines used in the $result.Get(X) are broken in Windows Server 2022, and have been for several months now.  This is a pretty big deal, considering the push in Azure to use the latest images.  No attention to this issue from the authors, it's a five minute fix.

**Comment by jabteles** [comment]
+1 preventing to migrate to Server 2022. No more workarounds.

**Comment by v-schhabra** [comment]
Hi @jabteles,
The mentioned issue has been fixed in this PR https://github.com/microsoft/azure-pipelines-extensions/pull/1220
Could you please use the IISWebAppManagementV3 version of the task and test if it is working fine?

**Comment by jabteles** [comment]
> Hi @jabteles, The mentioned issue has been fixed in this PR #1220 Could you please use the IISWebAppManagementV3 version of the task and test if it is working fine?

I updated the extension on my Azure DevOps and still get the same error. I've confirmed it is using correct version (3.2.0)

**Comment by v-schhabra** [comment]
@jabteles Could you please share the debugged logs?
