### ISSUE TITLE
Cannot show BitBucket Service Endpoint in Azure pipeline

### ISSUE THREAD

**Issue by blacktam** [microsoft/azure-pipelines-extensions#713]
I would like to use BitBucket Cloud for artifact source in Azure pipelines. Although I added the BitBucket service in project setting, it didn't show up in artifact source. 

I tried to add GitHub service in project setting, it could be showed up in artifact source

![image](https://user-images.githubusercontent.com/39482445/67826128-7acad700-fb06-11e9-84d0-fa862784b27c.png)

Would you mind let me know what the problem is ?

**Comment by romil07** [comment]
I am in the process of releasing a fix for this. Will update this thread when it's done.

**Comment by romil07** [comment]
This had been fixed in a later version of the extension. Closing this here.

**Comment by vsharma3112** [comment]
Do we have a new version rolled-out ? If not then is there any timeline ? We are on latest version - Installed version
15.157.0 (Latest) and this problem persists.

**Comment by NemoDima** [comment]
@romil07 @Lovakumar @chshrikh Could you check it, please?

BitBucket Service Endpoint hasn't been presented yet 
![image](https://user-images.githubusercontent.com/43349820/175311556-8b1fd62b-697a-4055-9ad9-aead50e10bae.png)
but is shown on the help pages:
https://github.com/Microsoft/azure-pipelines-extensions/blob/master/docs/authoring/artifactextension.md
https://github.com/Microsoft/azure-pipelines-extensions/tree/master/Extensions/BitBucket/Src

Thanks.
